forge "https://forgeapi.puppetlabs.com"
## The core OpenStack modules

mod "openstack-keystone", "6.0.0"
mod "openstack-swift", "6.0.0"
mod "openstack-glance", "6.0.0"
mod "openstack-cinder", "6.0.0"
mod "openstack-neutron", "6.0.0"
mod "openstack-nova", "6.0.0"
mod "openstack-heat", "6.0.0"
mod "openstack-ceilometer", "6.0.0"
mod "openstack-horizon", "6.0.0"
mod "openstack-openstacklib", "6.0.0"
mod "openstack-openstack_extras", "6.0.0"
mod "openstack-tempest", "6.0.0"
mod "openstack-vswitch", "2.0.0"
mod "puppetlabs-ntp"
mod "garethr-erlang"
mod "puppetlabs-mongodb"
